#pragma config(Sensor, port2,  colorSensorF,   sensorVexIQ_Color12Color)
#pragma config(Sensor, port3,  colorSensorB,   sensorVexIQ_Color12Color)
#pragma config(Sensor, port4,  distSensorF,    sensorVexIQ_Distance)
#pragma config(Sensor, port5,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port9,  distSensorB,    sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          leftDriveMotor, tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightDriveMotor, tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static float getDirection(void)
{
	const float drift=0.135;  /*deg/sec gyro drift*/
	return getGyroHeadingFloat(gyroSensor) - drift * time1[T4];
}

static void goForwardGyro(const float deg, const int ms)
{
	const int Fast = 50;
	const int Slow = 30;
	int speedRight = Fast;
	int speedLeft = Fast;
	setMotorSpeed(leftDriveMotor, speedLeft);
	setMotorSpeed(rightDriveMotor, speedRight);
	clearTimer(T1);
	while(time1[T1] < ms)
	{
		float direction = getDirection();
		if (direction > deg) {
			if (speedLeft != Fast) {
				speedLeft = Fast;
				setMotorSpeed(leftDriveMotor, speedLeft);
			}
			if (speedRight == Fast) {
				speedRight = Slow;
				setMotorSpeed(rightDriveMotor, speedRight);
			}
		} else if (direction < deg) {
			if (speedLeft == Fast) {
				speedLeft = Slow;
				setMotorSpeed(leftDriveMotor, speedLeft);
			}
			if (speedRight != Fast) {
				speedRight = Fast;
				setMotorSpeed(rightDriveMotor, speedRight);
			}
		} else {
			if (speedLeft != Fast) {
				speedLeft = Fast;
				setMotorSpeed(leftDriveMotor, speedLeft);
			}
			if (speedRight != Fast) {
				speedRight = Fast;
				setMotorSpeed(rightDriveMotor, speedRight);
			}
		}
	}
}
static void goBackwardGyro(const float deg, const int ms)
{
	const int Fast = -50;
	const int Slow = -30;
	int speedRight = Fast;
	int speedLeft = Fast;
	float direction;
	setMotorSpeed(leftDriveMotor, speedLeft);
	setMotorSpeed(rightDriveMotor, speedRight);
	clearTimer(T1);
	while(time1[T1] < ms)
	{
		direction = getDirection();
		if (direction > deg) {
			if (speedRight != Fast) {
				speedRight = Fast;
				setMotorSpeed(rightDriveMotor, speedRight);
			}
			if (speedLeft == Fast) {
				speedLeft = Slow;
				setMotorSpeed(leftDriveMotor, speedLeft);
			}
		} else if (direction < deg) {
			if (speedRight == Fast) {
				speedRight = Slow;
				setMotorSpeed(rightDriveMotor, speedRight);
			}
			if (speedLeft != Fast) {
				speedLeft = Fast;
				setMotorSpeed(leftDriveMotor, speedLeft);
			}
		} else {
			if (speedRight != Fast) {
				speedRight = Fast;
				setMotorSpeed(rightDriveMotor, speedRight);
			}
			if (speedLeft != Fast) {
				speedLeft = Fast;
				setMotorSpeed(leftDriveMotor, speedLeft);
			}
		}
	}
}

task main()
{
	getDirection();
	displaySensorValues(line1, gyroSensor);
	wait(5, seconds);
	goForwardGyro(90, 2500);
	goBackwardGyro(270, 2500);

}
