#pragma config(Sensor, port9,   L_LED,  sensorVexIQ_LED)
#pragma config(Sensor, port10,  R_LED,  sensorVexIQ_LED)
#pragma config(Sensor, port11,  GYRO,   sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,  R_LIFT, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,  L_TMOT, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,  R_MOT,  tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,  L_LIFT, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,  R_TMOT, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12, L_MOT,  tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static void goRight(const int ms)
{
	const int speed = 129;
	const int speedRight = speed;
	const int speedLeft = -speed;
	setMotorSpeed(L_MOT,speedLeft);
	setMotorSpeed(R_MOT,speedRight);
	setMotorSpeed(L_TMOT,speedLeft);
	setMotorSpeed(R_TMOT,speedRight);
	delay(ms);
}
static void goLeft(const int ms)
{
	const int speed = 129;
	const int speedRight = -speed;
	const int speedLeft = speed;
	setMotorSpeed(L_MOT,speedLeft);
	setMotorSpeed(R_MOT,speedRight);
	setMotorSpeed(L_TMOT,speedLeft);
	setMotorSpeed(R_TMOT,speedRight);
	delay(ms);
}
static void goForward(const int ms)
{
	const int speed = 129;
	const int speedRight = speed;
	const int speedLeft = speed;
	setMotorSpeed(L_MOT, speedLeft);
	setMotorSpeed(R_MOT, speedRight);
	setMotorSpeed(L_TMOT, speedLeft);
	setMotorSpeed(R_TMOT, speedRight);
	delay(ms);
}
static void goBackward(const int ms)
{
	const int speed = 129;
	const int speedRight = -speed;
	const int speedLeft = -speed;
	setMotorSpeed(L_MOT, speedLeft);
	setMotorSpeed(R_MOT, speedRight);
	setMotorSpeed(L_TMOT, speedLeft);
	setMotorSpeed(R_TMOT, speedRight);
	delay(ms);
}
static void goScoopwait(void)
{
	waitUntilMotorStop(L_LIFT);
	waitUntilMotorStop(R_LIFT);
}
static void goScoopUp(const int deg)
{
	const int speed = -50;
	setMotorTarget(L_LIFT, -deg, speed);
	setMotorTarget(R_LIFT, -deg, speed);
}
static void goScoopDown(const int deg)
{
	const int speed = 129;
	setMotorTarget(L_LIFT, -deg, speed);
	setMotorTarget(R_LIFT, -deg, speed);
}
static void goDump(void)
{
	goScoopUp(1025);
	goScoopwait();
	sleep(1250);
	goScoopDown(0);
	delay(500);
}
static void goStop(void)
{
	setMotorSpeed(L_MOT, 0);
	setMotorSpeed(R_MOT, 0);
	setMotorSpeed(L_TMOT, 0);
	setMotorSpeed(R_TMOT, 0);
}
static void goCourseRightBackward(const int ms)
{
	setMotorSpeed(R_MOT, -129);
	setMotorSpeed(R_TMOT, -129);
	delay(ms);
}
static void goCourseLeftBackward(const int ms)
{
	setMotorSpeed(L_MOT, -129);
	setMotorSpeed(L_TMOT, -129);
	delay(ms);
}
static void goCourseRightForward(const int ms)
{
	setMotorSpeed(R_MOT, 129);
	setMotorSpeed(R_TMOT, 129);
	delay(ms);
}
static void goCourseLeftForward(const int ms)
{
	setMotorSpeed(R_MOT, 129);
	setMotorSpeed(R_TMOT, 129);
	delay(ms);
}
static void goHome(const int ms)
{
	goStop();
	delay(ms);
}
static void anthony()
{
	goRight(1200);
	goForward(1800);
	goBackward(1500);
	goLeft(500);
	goForward(200);
	goLeft(200);
	goBackward(250);
	goLeft(500);
	goForward(2600);
	goBackward(450);
	goScoopUp(500);
	goStop();
	goScoopwait();
	goLeft(940);
	goForward(800);
	goBackward(1400);
	goLeft(600);
	goBackward(1450);
	goStop();
	goDump();
}
static void michael()
{
	goHome(6000);
	goLeft(1000);
	goForward(2250);
	goBackward(1375);
	goRight(500);
	goForward(200);
	goRight(200);
	goBackward(200);
	goRight(500);
	goForward(2700);
	goScoopUp(500);
	goBackward(500);
        goLeft(500);
        goForward(500);
        goRight(1000);
        goForward(1300);
	goBackward(1350);
	goRight(600);
	goBackward(1400);
	goStop();
	goDump();
}
static void resetDirection(void)
{
	resetGyro(GYRO);
	clearTimer(T4);
}
static float getDirection(void)
{
	const float drift=0.135;  /*deg/sec gyro drift*/
	return getGyroHeadingFloat(GYRO) - drift * time1[T4];
}
static void goForwardGyro(const float deg, const int ms)
{
	const int Fast = 129;
	const int Slow = 80;
	int speedRight = Fast;
	int speedLeft = Fast;
	setMotorSpeed(L_MOT, speedLeft);
	setMotorSpeed(R_MOT, speedRight);
	setMotorSpeed(L_TMOT, speedLeft);
	setMotorSpeed(R_TMOT, speedRight);
	clearTimer(T1);
	while(time1[T1] < ms)
	{
		float direction = getDirection();
		if (direction > deg) {
			if (speedLeft != Fast) {
				speedLeft = Fast;
				setMotorSpeed(L_MOT, speedLeft);
				setMotorSpeed(L_TMOT, speedLeft);
			}
			if (speedRight == Fast) {
				speedRight = Slow;
				setMotorSpeed(R_MOT, speedRight);
				setMotorSpeed(R_TMOT, speedRight);
			}
		} else if (direction < deg) {
			if (speedLeft == Fast) {
				speedLeft = Slow;
				setMotorSpeed(L_MOT, speedLeft);
				setMotorSpeed(L_TMOT, speedLeft);
			}
			if (speedRight != Fast) {
				speedRight = Fast;
				setMotorSpeed(R_MOT, speedRight);
				setMotorSpeed(R_TMOT, speedRight);
			}
		} else {
			if (speedLeft != Fast) {
				speedLeft = Fast;
				setMotorSpeed(L_MOT, speedLeft);
				setMotorSpeed(L_TMOT, speedLeft);
			}
			if (speedRight != Fast) {
				speedRight = Fast;
				setMotorSpeed(R_MOT, speedRight);
				setMotorSpeed(R_TMOT, speedRight);
			}
		}
	}
}
static void goBackwardGyro(const float deg, const int ms)
{
	const int Fast = -129;
	const int Slow = -80;
	int speedRight = Fast;
	int speedLeft = Fast;
	float direction;
	setMotorSpeed(L_MOT, speedLeft);
	setMotorSpeed(R_MOT, speedRight);
	setMotorSpeed(L_TMOT, speedLeft);
	setMotorSpeed(R_TMOT, speedRight);
	clearTimer(T1);
	while(time1[T1] < ms)
	{
		direction = getDirection();
		if (direction > deg) {
			if (speedRight != Fast) {
				speedRight = Fast;
				setMotorSpeed(R_MOT, speedRight);
				setMotorSpeed(R_TMOT, speedRight);
			}
			if (speedLeft == Fast) {
				speedLeft = Slow;
				setMotorSpeed(L_MOT, speedLeft);
				setMotorSpeed(L_TMOT, speedLeft);
			}
		} else if (direction < deg) {
			if (speedRight == Fast) {
				speedRight = Slow;
				setMotorSpeed(R_MOT, speedRight);
				setMotorSpeed(R_TMOT, speedRight);
			}
			if (speedLeft != Fast) {
				speedLeft = Fast;
				setMotorSpeed(L_MOT, speedLeft);
				setMotorSpeed(L_TMOT, speedLeft);
			}
		} else {
			if (speedRight != Fast) {
				speedRight = Fast;
				setMotorSpeed(R_MOT, speedRight);
				setMotorSpeed(R_TMOT, speedRight);
			}
			if (speedLeft != Fast) {
				speedLeft = Fast;
				setMotorSpeed(L_MOT, speedLeft);
				setMotorSpeed(L_TMOT, speedLeft);
			}
		}
	}
}

static void curveBackward(const int ms)
{
	setMotorSpeed(L_MOT, -100);
	setMotorSpeed(L_TMOT, -129);
	setMotorSpeed(R_MOT, -129);
	setMotorSpeed(R_TMOT, -100);
	delay(ms);
}
static void curveBackward2(const int ms)
{
	setMotorSpeed(L_TMOT, -100);
	setMotorSpeed(L_MOT, -129);
	setMotorSpeed(R_TMOT, -129);
	setMotorSpeed(R_MOT, -100);
	delay(ms);
}

static void ramp(void)
{
	goHome(10000);
	resetDirection();
	goForward(1500);
	goLeft(550);
	goScoopUp(200);
	goForwardGyro(90, 4700);
	goScoopDown(0);
	goHome(30000000);
}


task main()
{
	resetDirection();
	anthony();
	//michael();
	//ramp();
}